### ISSUE TITLE
Configurar continuous delivery

### ISSUE THREAD

**Issue by fcoclavero** [pastagil/pastagil_todolist#11]
Como: usuario que quiere usa la solución

Quiero:  tener acceso a los nuevos features de la solución

Para: poder sacarle provecho a las nuevas funcionalidades

**Comment by sfehlandt** [comment]
Closed by: 061276762416ba88a474f503999bddd105bd0b9b

**Comment by sfehlandt** [comment]
Closed by: 061276762416ba88a474f503999bddd105bd0b9b
