### ISSUE TITLE
Soportar edición de Tasks

### ISSUE THREAD

**Issue by fcoclavero** [pastagil/pastagil_todolist#8]
Como: usuario que se equivoca en describir sus tareas

Quiero: poder editar una tarea

Para: tener una descripción apropiada

**Comment by fcoclavero** [comment]
El usuario debe poder:
* Marcar como completada
* Cambiar el texto

**Comment by fcoclavero** [comment]
- [ ] Flag completado (?)
- [ ] Tests modelo
- [ ] Tests vista
- [ ] Vista de edición
- [ ] Agregar acceso a TaskListView

**Comment by sfehlandt** [comment]
Limitar a edición de texto, Flag completado se tratará en otra historia de usuario
